# Generated by Django 3.2.2 on 2021-05-22 20:07

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='رایانامه')),
                ('username', models.CharField(max_length=60, unique=True, verbose_name='نام کاربری')),
                ('phone', models.CharField(max_length=25, unique=True, verbose_name='تلفن همراه')),
                ('address', models.TextField(help_text='لطفا آدرس مزرعه یا باغ را وارد کنید', verbose_name='آدرس مزرعه')),
                ('date_joined', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ عضویت')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='آخرین بازدید')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('products', models.TextField(blank=True, help_text='چه گیاهان و بذر هایی کشت میکنید', null=True, verbose_name='توضیحات')),
                ('area', models.PositiveIntegerField(blank=True, help_text='لطفا مساحت باغ یا سطح زیر کشت را وارد کنید', null=True, verbose_name='مساحت ')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326, verbose_name='مزرعه من')),
                ('hide_email', models.BooleanField(default=True)),
                ('hide_phone', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
