# Generated by Django 3.2.2 on 2021-05-29 17:22

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='layers',
            fields=[
                ('layer_id', models.AutoField(primary_key=True, serialize=False)),
                ('layer_name', models.CharField(max_length=50)),
                ('workspace', models.CharField(max_length=50)),
                ('layer_alias', models.CharField(max_length=50)),
                ('server_address', models.URLField()),
                ('userOwner', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='drawing',
            fields=[
                ('geomId', models.AutoField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('userOwner', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
